# Generated by Django 5.0.4 on 2024-04-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_password',
            field=models.CharField(blank=True, null=True, verbose_name='ключ для верификации'),
        ),
    ]
