# Generated by Django 5.0.4 on 2024-04-18 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AddField(
            model_name='comment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.lesson', verbose_name='урок'),
        ),
        migrations.AddField(
            model_name='theme',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AddField(
            model_name='theme',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.subject', verbose_name='предмет'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.theme', verbose_name='тема'),
        ),
        migrations.AddField(
            model_name='comment',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.theme', verbose_name='тема'),
        ),
    ]
