# Generated by Django 5.0.4 on 2024-04-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'permissions': [('set_published', 'Can publish lesson')], 'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'предмет', 'verbose_name_plural': 'предметы'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'permissions': [('set_published', 'Can publish theme')], 'verbose_name': 'тема', 'verbose_name_plural': 'темы'},
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время'),
        ),
    ]
