# Generated by Django 5.0.4 on 2024-04-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_comment_user_alter_lesson_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/', verbose_name='файл с уроком'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='link_video',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ссылка на видео'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='material',
            field=models.TextField(blank=True, null=True, verbose_name='материал'),
        ),
    ]
