# Generated by Django 5.0.4 on 2024-04-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_lesson_file_lesson_link_video_lesson_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='текст комментария'),
        ),
    ]
