# Generated by Django 5.0.4 on 2024-04-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_comment_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
