# Generated by Django 5.0.4 on 2024-04-23 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('materials', '0008_question_answer_testpaper_result_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.testpaper', verbose_name='тест'),
        ),
    ]
