# Generated by Django 5.0.4 on 2024-04-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_testpaper_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(verbose_name='верный'),
        ),
    ]
